# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ybiraabU5BCAsls3JHMVVNjs8IQm84Se
"""

import streamlit as st
from scraper import scrape_multiple_sites, save_to_csv, save_to_excel

st.title("Raspagem de Dados de Brinquedos")

url_input = st.text_area("Insira as URLs dos sites (separados por vírgula)")
urls = [url.strip() for url in url_input.split(',') if url.strip()]

if st.button("Iniciar Raspagem"):
    if urls:
        scraped_data = scrape_multiple_sites(urls)
        st.success("Raspagem concluída!")

        csv = save_to_csv(scraped_data)
        excel = save_to_excel(scraped_data)

        st.download_button(label="Baixar dados em CSV", data=csv, file_name='dados_raspados.csv', mime='text/csv')
        st.download_button(label="Baixar dados em Excel", data=excel, file_name='dados_raspados.xlsx', mime='application/vnd.ms-excel')

        st.write(scraped_data)
    else:
        st.error("Por favor, insira ao menos uma URL.")